/*
 * This source file was generated by the Gradle 'init' task
 */
package com.upsjb.Sesion09F;


import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.upsjb.Sesion09F.vistasUI.JFInicio;

import com.upsjb.Sesion09F.vistasUI.UIMENU;
import javax.swing.UIManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
            var ventana= new JFInicio();
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        } catch (Exception e) {
        }
    }
}
